# Database Configuration - RC: In production, these should be set via environment variables and not hardcoded defaults.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/asset_management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345} 
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# App name
spring.application.name=asset-maintenance

# Server port
server.port=${PORT:8080}

# JWT Config - RC: In production, these should be set via environment variables and not hardcoded defaults. missing env var on render or vercel would silently use these with no warning.
jwt.secret=${JWT_SECRET:asset-maintenance-super-secret-key-2026-very-long} 
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging.level.org.springframework.security=INFO
logging.level.com.siemens.asset_maintenance=INFO