# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/asset_maintenance
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App name
spring.application.name=asset-maintenance

# Server port
server.port=8080

# JWT Config
jwt.secret=your-super-secret-key-must-be-at-least-32-characters-long
jwt.expiration=86400000

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging.level.org.springframework.security=DEBUG
logging.level.com.siemens.asset_maintenance=DEBUG